name: sirf

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  farm:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Farm
        run: python script.py --headless --fast

      - name: Save logs.txt as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs.txt

      - name: Upload logs to Telegram
        if: always()
        run: bash tgs

      - name: Remove logs.txt
        if: always()
        run: rm logs.txt